/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/fox_shield/scene.gltf 
Author: Eques_inferno (https://sketchfab.com/Eques_inferno)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-shield-462d3296495944f890e24749d251c573
Title: Fox shield
*/

import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useEffect, useRef } from "react";

export function Fox(props) {
  const { nodes, materials } = useGLTF("/public/models/fox_shield/scene.gltf");
  const ref = useRef(null);
  const tl = useRef(null);
  useEffect(() => {
    tl.current = gsap.timeline();

    const ctx = gsap.context(() => {
      tl.current.to(
        ref.current.rotation,
        {
          y: 5,
          x: -0.7,
          duration: 1,
          scrollTrigger: {
            trigger: "#foxContainer3D",
            start: "50% 80%",
            end: "90% top",
            scrub: 1,
          },
        },
        0
      );
      tl.current.to(
        ref.current.position,
        {
          y: -3.5,
          duration: 1,
          scrollTrigger: {
            trigger: "#foxContainer3D",
            start: "50% bottom",
            end: "80% top",
            scrub: 1,
          },
        },
        0
      );
    });
    return () => ctx.revert();
  }, []);

  return (
    <group
      ref={ref}
      scale={(10, 10, 10)}
      rotation={[0, -1.5, 0]}
      position={[0, 1, 0]}
      {...props}
      dispose={null}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.021}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Fox_low_lambert1_0.geometry}
            material={materials.lambert1}
            position={[0.051, -0.367, 0]}
            rotation={[0, 0, -0.021]}
          />
          <mesh
            geometry={nodes.handle2_low_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-0.425, 4.312, 1.242]}
            rotation={[0, -0.18, 0]}
            scale={[0.412, 0.69, 0.622]}
          />
          <mesh
            geometry={nodes.handle1_low_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-0.491, 7.457, 2.019]}
            rotation={[0, -0.107, 0]}
            scale={[0.418, 0.69, 1.001]}
          />
          <mesh
            geometry={nodes.Metal_low_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.shield_low_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/fox_shield/scene.gltf");
